//ws module
var WebSocket = require('ws');
var WebSocketServer = WebSocket.Server;
var port = 3001;
var ws = new WebSocketServer({
port: port
});
//creating arrary to hold on to messages, but no DB so we do this
var messages = [];
console.log('websockets server started');

//establish callback for any connection events for my WS server
ws.on('connection', function (socket) {
    console.log('client connection established');
//allow new users to see all previous messages
//when connection made, server iterates through messages and sends
//each one to the new connection
    messages.forEach(function (msg) {
        socket.send(msg);
        });
//server to repeat any messages sent to it
//Known as echo server
//registering callback for any message events generated by
//client connection then the server with wscat
    socket.on('message', function (data) {
        console.log('message received: ' + data);
        //add each message to the array as it arrives
        messages.push(data);
        //send new messages to all users as each new message comes in
        ws.clients.forEach(function (clientSocket) {
            clientSocket.send(data)
            });
    });
    });